### ISSUE TITLE
authorisation token expired

### ISSUE THREAD

**Issue by seliver** [adammhaile/Elpis#10]
Operating System Version?:
iwndows xp pro 
vs 2002
service pack 3

Elpis Version?:
1.4.5.0

Country and do you use a Proxy?:
USA
no
What steps will reproduce the problem?
1.leave it on over night
2.or longer than 5 or 6 hours
3.

What is the expected output? What do you see instead?:
silence
warning thingy

Please provide any additional information below.
************************************************
PandoraSharp.Exceptions.PandoraException: Auth token is invalid/expired.
   at PandoraSharp.Pandora.HandleFaults(JSONResult result, Boolean secondTry)
   at PandoraSharp.Pandora.CallRPC(String method, JObject request, Boolean isAuth, Boolean useSSL)
   at PandoraSharp.Pandora.Search(String query)
   at PandoraSharpPlayer.Player.<>c__DisplayClass15.<StationSearchNew>b__14()
   at PandoraSharpPlayer.Player.<>c__DisplayClass1.<RunTask>b__0()

**Comment by seliver** [comment]
never happened.
