### ISSUE TITLE
Pandora stream unable to load

### ISSUE THREAD

**Issue by kuojo** [adammhaile/Elpis#130]
PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_FILEFORM
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass168_0.<RunTask>b__0()

**Comment by kuojo** [comment]
I get this error when I attempt to load the station

**Comment by kuojo** [comment]
This was causes by a proxy configuration issue. No bug here. My bad
