### ISSUE TITLE
Error on open: "Error initializing the player engine"

### ISSUE THREAD

**Issue by LifeDay** [adammhaile/Elpis#133]
Operating System: Windows 10
Current Elpis Version: 1.5.2
Using proxy/vpn: No
Steps to reproduce the problem: Start the software
Problem:
Elpis opens with the message:
"All hope is lost,
the box is open!
Error initializing the player engine, Elpis must close. Try restarting the application.
This error is not recoverable. Press "Close" to quit the application."

Error details:
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_DRIVER
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by seliver** [comment]
Is it still happening?
Try deleting the config file and trying again.

**Comment by LifeDay** [comment]
I deleted the config file and got the same message.
I then uninstalled and reinstalled and I'm still getting the same error.

**Comment by cpramodroy** [comment]
![image](https://cloud.githubusercontent.com/assets/17915583/18148729/54ba3e66-6f90-11e6-851c-d54498cbdd9a.png)

Still having the same issue. I tried installing 1.5.0 as well multiple times but still crashes. Also, I had a much older version, I think 1.3.2 if I'm not wrong and when I updated my system to windows 10 the application ported too and was working perfectly fine. For some reason, I had to uninstall the application and when I tried installing 1.5.2 and 1.5.0 it keeps crashing.

**Comment by seliver** [comment]
Well, lets try uninstalling the .NET and installing the 4.5 version.
