### ISSUE TITLE
End of playlist detected.  Skip limit exceeded.

### ISSUE THREAD

**Issue by ccyr0509** [adammhaile/Elpis#134]
I started getting this issue at the end of last week.  I am not using any skips that I'm aware of.  I will double check my hotkeys, but I'm not skipping any songs that I know of.  A restart of the client seems to fix the issue temporarily.  This time it happened after just two songs.  Any advice would be great.  Thanks!

PandoraSharp.Exceptions.PandoraException: End of playlist detected. Skip limit exceeded.
   at PandoraSharpPlayer.Playlist.WaitForPlaylistReload()
   at PandoraSharpPlayer.Playlist.DoReload()
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.<bass_PlaybackStateChanged>b__27()
   at PandoraSharpPlayer.Player.<>c__DisplayClass3.<RunTask>b__2()

**Comment by ccyr0509** [comment]
Now it says Failed to load song more than once.  Check connection and try again.  After restarting and playing one song.

PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_FILEOPEN
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.<bass_PlaybackStateChanged>b__27()
   at PandoraSharpPlayer.Player.<>c__DisplayClass3.<RunTask>b__2()

**Comment by ccyr0509** [comment]
Now I can't get any station to load because the skip limit has been reached.

**Comment by seliver** [comment]
How about now?
As I have seen on other related issues, you just have to give it some time. It's not an Elpis issue, but a Pandora ones.

**Comment by Firedingo** [comment]
I have this issue. Been a good 6 hours at least since I last used the player and after 1 song it said End of Playlist, Skip Limit Exceeded. Even restarting the player didn't help. It also refuses to login if you have reload last station played on start as that throws the error and prevents the login from working.
