### ISSUE TITLE
Failed to load song more than once.

### ISSUE THREAD

**Issue by Mithradatha** [adammhaile/Elpis#150]
OS: ***Windows 10*** (Anniversary Update from 8.1)
Elpis Version: ***1.5.2.0***

`Steps to replicate:`
1. Start Elpis
2. Click on any station in station list
3. Progress/Loading circle continues to spin until warning

`Error Detail:`
PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_TIMEOUT
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass168_0.<RunTask>b__0()

**Comment by Mithradatha** [comment]
Flash Player Update
