### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by jevdemon** [adammhaile/Elpis#151]
I started up Elpis, clicked options and changed Station Sort Order from Alphabetical Ascending to Rating Ascending.  A red triangle appeared.  When I clicked on it the following exception appeared:

System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PandoraSharp.Pandora.<GetStationMetaData>b__96_0(Station station)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at PandoraSharp.Pandora.GetStationMetaData()
   at PandoraSharp.Pandora.RefreshStations()
   at PandoraSharpPlayer.Player.<RefreshStations>b__187_0()
   at PandoraSharpPlayer.Player.<>c__DisplayClass168_0.<RunTask>b__0()
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at PandoraSharp.Pandora.<GetStationMetaData>b__96_0(Station station)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

**Comment by jevdemon** [comment]
Tried re-installing, still happening.  Running Win10 Ver 1607 (OS Build 14965.1001)

**Comment by jevdemon** [comment]
This seemed to be a problem with my account.  I logged in with a different Pandora account and it's working well. Thanks for creating this tool!

**Comment by seliver** [comment]
Try deleting the configuration files. They're located at
C:\Users\<YOUR_USERNAME>\AppData\Roaming\Elpis

The file to rename(just in case you might need the old configuration) is
the elpis.config
After that just try to open Elpis again.
