### ISSUE TITLE
Elipis crashed - don't know why

### ISSUE THREAD

**Issue by pgorbas** [adammhaile/Elpis#154]
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

Was playing fine, then it stopped playing.  I killed the no working task in task manager, and when I restart I get this message.  Tried again and a third time, same result.  Every time it 'closes' it leave a remnant in the task manager details.

Runing windows 10.   Pandora still plays fine through windows 10 app

**Comment by seliver** [comment]
Try deleting the configuration files. They're located at
C:\Users\<YOUR_USERNAME>\AppData\Roaming\Elpis

The file to rename(just in case you might need the old configuration) is
the elpis.config
After that just try to open Elpis again.

**Comment by redolencetech** [comment]
Can reproduce this error, and have renamed `elpis.config`

**Comment by Xbye** [comment]
I am currently having the same error -
> BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

Was working fine last night. Tried the fix mentioned by @seliver and didn't work.

Seems this GitHub is dead though so I guess that's enough free radio for me. Another app dead in the sea of apps to listen to Pandora without obnoxious ads.

**Comment by Wires77** [comment]
@Xbye I can maybe take a look at this error.  It's pretty hard to reproduce as far as I can tell because the error is literally an internal library error.  Do all the versions of Elpis fail like this or just the latest one?

**Comment by Xbye** [comment]
@Wires77 
Thanks!

Seems the error fixed itself over time... now I am getting a new error whenever I try to play a station.

>PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_FILEOPEN
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass168_0.<RunTask>b__0()

Haven't been able to use Elpis for 3 days now because it won't play a station.

**Comment by Wires77** [comment]
@Xbye Can you edit your elpis.config and change Debug_WriteLog|False to True?  Then run Elpis and find the log file where the config file is stored.  Attach it here when you're done.
