### ISSUE TITLE
Unable to play any songs due to an unhandled exception

### ISSUE THREAD

**Issue by jevdemon** [adammhaile/Elpis#155]
Error is below.  Unsure of cause.  I have another 3rd party Pandora tool that is working fine with the same account (although I prefer Elpis).

PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_FILEOPEN
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass168_0.<RunTask>b__0()

**Comment by jevdemon** [comment]
Spoke too soon - I deleted my config file at C:\Users\<user>\AppData\Roaming\Elpis\elpis.config and re-started Elpis so it would be recreated.  Problem solved!  
Thanks again for this great tool.
