### ISSUE TITLE
Bass_Error_Unknown

### ISSUE THREAD

**Issue by SteveMelb** [adammhaile/Elpis#168]
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

I have tried renaming/deleting the elpis.config file in the appData/Roaming folder to no avail as suggested in another occurrence.

**Comment by SteveMelb** [comment]
Restarted the PC and the issue has gone.
