### ISSUE TITLE
Error at startup - BASS_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by seliver** [adammhaile/Elpis#17]
Expected: Normal startup.

Instead: BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by seliver** [comment]
This error is caused by the Windows Audio service not running.  Or at least, that's one potential cause - I enabled WAS and stopped getting this error.

The best behavior would be similar to that of opening the sound control panel - "Windows Audio Service is not running, would you like to start it now?"  A fallback would be just alerting the user to what needs to be done.
