### ISSUE TITLE
Error initializing the player engine. Elpis must Close. Try restarting the application.

### ISSUE THREAD

**Issue by crckrmn77** [adammhaile/Elpis#187]
Just updated to 1.6.0, and now on startup I get this error every time:

BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

Also, process will not close after closing the program???

Operating System: Windows 7 x64

Current Elpis Version: 1.6.0 (also had a similar error in 1.5.0, but restarting process would fix it)

Using proxy/vpn: No

Steps to reproduce the problem: Load the program. Does it every time.

Problem: Elpis fails to start.

**Comment by Wires77** [comment]
Hmm, that's certainly odd.  Could you open your elpis.config file (Should be under %AppData%/Elpis) and add the line "Debug_WriteLog|True"?  Then run Elpis, find the log file in that same directory, and put it here.

My first suspicion is something to do with Windows 7, but I can't confirm until I see that.

**Comment by cbjjensen** [comment]
I'm getting this issue on Windows 10. I tried settin gthe value of Debug_WriteLog to True, but I am given the same error back.

BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by cbjjensen** [comment]
I believe I have found the global resolution to this issue. I think there is something broken within Windows itself. For some reason ALL sound stopped working on my system (weird that this is affecting other users at the same time?) 

I ran through the **Restart Windows Audio Service** steps, and it resolved the error!

https://www.drivereasy.com/knowledge/solved-failed-to-play-test-tone/

**Comment by KWottrich** [comment]
I also had the exact error message in the first post.  I restarted the Windows Audio service, as it directs in cbjjensen's link (I didn't need to do any of the other steps though), and restarted Elpis, and that fixed my issue.

**Comment by mouseas** [comment]
I've also had this issue, it tends to happen which I launch Elpis immediately after starting up, but I don't have enough data points to be sure of that.

I have a secondary issue to report, which occurs right after this bug happens: When I restart Elpis, it defaults back to 100% volume, which can be jarring since I keep it around 20%. I haven't noticed any other settings revert when this happens.

**Comment by Wires77** [comment]
@mouseas I can't replicate your volume issue unfortunately, and from what I can tell the volume will always load from the config file.

As for this other audio issue, I'll direct people here to see if it helps going forward.  I've never had this issue personally, and it sounds pretty intermittent, but if anyone can consistently reproduce it I'd be all ears.

**Comment by AeSix** [comment]
Just had this issue *again*
After a Windows 10 update and restart. 
After any restart, my USB speaker is not recognized.  (iEnjoy cube) - I blame the device, because it happens on Win7, Win8.1 and WIn10 (every update).  

I resolve it by turning the speaker off and back on, which forces Windows to re-recognize the speaker.  After doing this, Elpis works again.  

Maybe a "Check that your speakers are working and connected" message may be good?
