### ISSUE TITLE
Failed to load song more than once.

### ISSUE THREAD

**Issue by astraTiCon** [adammhaile/Elpis#190]
Operating System: Win 10
Current Elpis Version: 1.6.0.0
Using proxy/vpn: yes
Steps to reproduce the problem: none, seems to happen randomly
Problem: Elpis stops playing

PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_TIMEOUT
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.<bass_PlaybackStateChanged>b__27()
   at PandoraSharpPlayer.Player.<>c__DisplayClass3.<RunTask>b__2()

**Comment by seliver** [comment]
this is a duplicate of #34 
not an Elpis problem.

**Comment by sclient** [comment]
My theory is that they have added some new detection for when ads fail to play (for me it fixes if I reload elpis, but sometimes it can happen after only 2-3 songs have played, so its pretty frustrating). It even happens in my browser now with ublock origins.
