### ISSUE TITLE
Player Failed to Initialize

### ISSUE THREAD

**Issue by seanaawa** [adammhaile/Elpis#199]
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by cbjjensen** [comment]
See issue https://github.com/adammhaile/Elpis/issues/187
