### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by foxtwo7** [adammhaile/Elpis#203]
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by andytruett** [comment]
Same error here, ending the Elpis task and restarting got it working again.
