### ISSUE TITLE
Init Error: BASS_ERROR_DRIVER

### ISSUE THREAD

**Issue by nmalinowski** [adammhaile/Elpis#207]
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_DRIVER
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by davidedmonson** [comment]
I can confirm the same bug;

Windows 10 64bit and this error just started happening.

**Comment by TheTonker** [comment]
Ditto.  I just noticed the error details (I made a new ticket).

PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_TIMEOUT
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.<Next>b__25()
   at PandoraSharpPlayer.Player.<>c__DisplayClass3.<RunTask>b__2()

**Comment by cbjjensen** [comment]
https://github.com/adammhaile/Elpis/issues/187

**Comment by sclient** [comment]
Just tried restarting it twice from windows services in 8.1. Error:
PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_TIMEOUT
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass3.<RunTask>b__2()

**Comment by Wires77** [comment]
@sclient Is it possible something happened with your Pandora account?  You mentioned two other apps have stopped working as well.

**Comment by sclient** [comment]
No problem with the official webapp. Im going to try rebooting just in case. Tried a bunch of different stuff in that article as well.

**Comment by Wires77** [comment]
@sclient Can you go into your configuration settings and add "Debug_WriteLog|True" for me?  It should be located in %AppData%/Elpis.  Then post the debug log from the same filepath after it crashes (be sure to remove your e-mail from the output).

I'm wondering if I've never come across this issue because I don't play Elpis constantly during the day and it is related to some skip limit.  There are two different errors occurring here, one related to failing to play a song (possibly being ad-related), and the other relating to the services.msc I believe.  I cannot reproduce either error unfortunately, but hopefully your debug log will shed some light on things.

**Comment by cbjjensen** [comment]
Try the solution from here: https://github.com/adammhaile/Elpis/issues/187
