### ISSUE TITLE
Intermittent Error - Player stops and goes back to radio list

### ISSUE THREAD

**Issue by TheTonker** [adammhaile/Elpis#208]
Once an a while the audio just cuts out and will not play the next song.  Any radio channel I choose does this.  Sometimes it's after 1 song, sometime a couple of songs.  Very random.

Error details:
PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_TIMEOUT
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.<Next>b__25()
   at PandoraSharpPlayer.Player.<>c__DisplayClass3.<RunTask>b__2()

**Comment by sclient** [comment]
To me it seems like pandora has added some detection for when ads are supposed to play and they dont. Even on the web client with ublock origins, I sometimes have to reload 2x after skipping a song (or it just hangs when the ad fails to play).

**Comment by cbjjensen** [comment]
See issue; https://github.com/adammhaile/Elpis/issues/187 for fix.
