### ISSUE TITLE
Too much BASS to handle into one box.

### ISSUE THREAD

**Issue by Dudemas** [adammhaile/Elpis#215]
My bass audio is _**too swole**_ and cannot be controlled.
Merci beaucoup.

BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by cbjjensen** [comment]
https://github.com/adammhaile/Elpis/issues/187
