### ISSUE TITLE
Launcher told me to come here

### ISSUE THREAD

**Issue by Chefbarbie** [adammhaile/Elpis#221]
Won't launch, throws this error. 
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by davidpryke** [comment]
Same here:

> BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
>    at BassPlayer.BassAudioEngine.InitBass()
>    at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
>    at Elpis.MainWindow.FinalLoad()

**Comment by kopper42** [comment]
I'm getting this as well.  Looking at the code, it seems to be having trouble opening the default audio device.  This started happening for me just recently.  I did just start using VoiceMeeter Banana and I suspect it may have something to do with it.  Have you recently changed anything to do with your audio drivers or audio setup in general?
