### ISSUE TITLE
Can't connect to stations

### ISSUE THREAD

**Issue by DougOH** [adammhaile/Elpis#225]
PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_TIMEOUT
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass3.<RunTask>b__2()

**Comment by DougOH** [comment]
Program loads and seems to login OK.   When loading a station it fails.   This just started maybe a week ago.   I'm running Win 7 x64 with the current .net.    I see nothing in firewall thats an issue.
