### ISSUE TITLE
Error initializing not sure what caused it

### ISSUE THREAD

**Issue by Brock09** [adammhaile/Elpis#228]
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by TheTonker** [comment]
Same issue with me.  Uninstalled and reinstalled and still nothing.  Using chrome now with ad blocker block ads but I can't skip forever.

PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_TIMEOUT
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass3.<RunTask>b__2()
