### ISSUE TITLE
Error Initializing Player Engine

### ISSUE THREAD

**Issue by yancebrett** [adammhaile/Elpis#233]
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_DRIVER
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by yancebrett** [comment]
Duplicate. Sorry.
