### ISSUE TITLE
Elpis 1.46, 1.47 and 1.48 crash on Windows 10 Build 10041

### ISSUE THREAD

**Issue by kbchurch** [adammhaile/Elpis#44]
I'm aware Win 10 is a moving target now in technical preview, but just in case it's something on Elpis' side...

Upon open, the Elpis window with the rotating progress and the words "Checking for Updates..." appears and the application goes no further. The Windows "Elpis has stopped working" window immediately opens and starts to 'search' for a solution. Multiple reinstalls do not fix the problem.

Information from the Event Log (thanks for looking):

**Windows Error Reporting:**

Fault bucket 73950334707, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 73094128305

Problem signature:
P1: Elpis.exe
P2: 1.4.8.0
P3: 5501e323
P4: ws2_32.dll
P5: 10.0.10041.0
P6: 5503ab43
P7: c0000005
P8: 000060ab
P9: 
P10: 

Attached files:
C:\Users\Brent\AppData\Local\Temp\WER3896.tmp.WERInternalMetadata.xml
C:\Users\Brent\AppData\Local\Temp\WER4440.tmp.appcompat.txt
C:\Users\Brent\AppData\Local\Temp\WER4460.tmp.hdmp
C:\Users\Brent\AppData\Local\Temp\WER5D0A.tmp.WERDataCollectionFailure.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9a43d7bc-cf08-11e4-ab60-000272c8aef6
Report Status: 8
Hashed bucket: 7e74a44bf37a7791ae94437eeeaed4b1

**Application Error**

Faulting application name: Elpis.exe, version: 1.4.8.0, time stamp: 0x5501e323
Faulting module name: ws2_32.dll, version: 10.0.10041.0, time stamp: 0x5503ab43
Exception code: 0xc0000005
Fault offset: 0x000060ab
Faulting process id: 0x1ee0
Faulting application start time: 0x01d06315ed13e81b
Faulting application path: C:\Program Files (x86)\Elpis\Elpis.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ws2_32.dll
Report Id: 2b9a024c-cf09-11e4-ab60-000272c8aef6
Faulting package full name: 
Faulting package-relative application ID: 

**.NET Runtime**

Application: Elpis.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
Stack:
   at System.Net.UnsafeNclNativeMethods+SafeNetHandlesXPOrLater.GetAddrInfoW(System.String, System.String, System.Net.AddressInfo ByRef, System.Net.SafeFreeAddrInfo ByRef)
   at System.Net.Dns.TryGetAddrInfo(System.String, System.Net.AddressInfoHints, System.Net.IPHostEntry ByRef)
   at System.Net.Dns.TryInternalResolve(System.String, System.Net.IPHostEntry ByRef)
   at System.Net.ServicePoint.GetIPAddressInfoList(Int32 ByRef, System.Net.IPAddress[])
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean, System.Net.Sockets.Socket, System.Net.Sockets.Socket, System.Net.Sockets.Socket ByRef, System.Net.IPAddress ByRef, ConnectSocketState, System.IAsyncResult, System.Exception ByRef)
   at System.Net.ServicePoint.GetConnection(System.Net.PooledStream, System.Object, Boolean, System.Net.IPAddress ByRef, System.Net.Sockets.Socket ByRef, System.Net.Sockets.Socket ByRef)
   at System.Net.PooledStream.Activate(System.Object, Boolean, System.Net.GeneralAsyncDelegate)
   at System.Net.Connection.CompleteStartConnection(Boolean, System.Net.HttpWebRequest)
   at System.Net.Connection.CompleteStartRequest(Boolean, System.Net.HttpWebRequest, System.Net.TriState)
   at System.Net.Connection.SubmitRequest(System.Net.HttpWebRequest, Boolean)
   at System.Net.ServicePoint.SubmitRequest(System.Net.HttpWebRequest, System.String)
   at System.Net.HttpWebRequest.SubmitRequest(System.Net.ServicePoint)
   at System.Net.HttpWebRequest.BeginGetResponse(System.AsyncCallback, System.Object)
   at System.Net.WebClient.DownloadBits(System.Net.WebRequest, System.IO.Stream, System.Net.CompletionDelegate, System.ComponentModel.AsyncOperation)
   at System.Net.WebClient.DownloadStringAsync(System.Uri, System.Object)
   at System.Net.WebClient.DownloadStringAsync(System.Uri)
   at Elpis.UpdateSystem.UpdateCheck.DownloadString(System.String, Int32)
   at Elpis.UpdateSystem.UpdateCheck.CheckForUpdateInternal(Boolean)
   at Elpis.MainWindow.LoadLogic()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by seliver** [comment]
OK looks like something with the webclient on windows 10 doesn't work. As of now, i have no plans nor time to install windows 10 to test it. What you can do for now is install visual studio on your O.S. and comment the lines that are responsible for update check.

**Comment by kbchurch** [comment]
I'll get to that when I can. It's likely the an update or new build will restore it and I'll let you know then.

**Comment by seliver** [comment]
OK thanks!

**Comment by seliver** [comment]
One more issue of Elpis problems on Windows 10: https://github.com/adammhaile/Elpis/issues/60

**Comment by kbchurch** [comment]
For me my issue was solved. I ended up doing a complete reinstall and it cleared up the issue. My guess is something unique to my setup and not necessarily to Windows 10 was the issue. For now I have no issues with Elpis.

**Comment by seliver** [comment]
Very glad to hear that! Will close this then.
