### ISSUE TITLE
Elpis can't start "All hope is lost" error

### ISSUE THREAD

**Issue by pgorbas** [adammhaile/Elpis#94]
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by seliver** [comment]
This is a duplicate of issue #32 . Closing this.
