### ISSUE TITLE
Elpis crashes in Windows 10

### ISSUE THREAD

**Issue by bkilpat01** [adammhaile/Elpis#95]
Elpis crashes immediately upon opening. I get the following error:

BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by seliver** [comment]
This is another duplicate of issue #32 . Not an Elpis problem, basically. Wait a few days and it will start working again.
