### ISSUE TITLE
Elpis will not launch even after restarting application

### ISSUE THREAD

**Issue by joshsharrer** [adammhaile/Elpis#99]
BassPlayer.BassException: BASS: Initialize failed. Reason: }Init Error: BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.InitBass()
   at PandoraSharpPlayer.Player.Initialize(String bassRegEmail, String bassRegKey)
   at Elpis.MainWindow.FinalLoad()

**Comment by seliver** [comment]
Hi. Thanks for reporting, but this is one of those problems not really related to Elpis, but to Pandora itself. Check out issue #32.
